"""criacao de tabelas

Revision ID: 5428769fbcf4
Revises: 44a818904a47
Create Date: 2021-12-01 22:21:43.974471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5428769fbcf4'
down_revision = '44a818904a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_tech',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['tech.id'], ),
    sa.PrimaryKeyConstraint('developer_id', 'tech_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_tech')
    # ### end Alembic commands ###
