"""criacao de tabelas

Revision ID: 86196d74256d
Revises: 5428769fbcf4
Create Date: 2021-12-01 22:25:23.839238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86196d74256d'
down_revision = '5428769fbcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer', sa.Column('age', sa.Integer(), nullable=False))
    op.drop_column('developer', 'idade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer', sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('developer', 'age')
    # ### end Alembic commands ###
